export const USER_SUBSCRIBE_REQUEST = 'USER_SUBSCRIBE_REQUEST';
export const USER_SUBSCRIBE_SUCCESS = 'USER_SUBSCRIBE_SUCCESS';
export const USER_SUBSCRIBE_FAIL = 'USER_SUBSCRIBE_FAIL';

export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';
export const ADMIN_CLEAR_TOKEN = 'ADMIN_CLEAR_TOKEN';
export const ADMIN_CLEAR_SENDMAIL_ERROR = 'ADMIN_CLEAR_SENDMAIL_ERROR';

export const ADMIN_SENDMAIL_REQUEST = 'ADMIN_SENDMAIL_REQUEST';
export const ADMIN_SENDMAIL_SUCCESS = 'ADMIN_SENDMAIL_SUCCESS';
export const ADMIN_SENDMAIL_FAIL = 'ADMIN_SENDMAIL_FAIL';
